### ISSUE TITLE
Add the feature to dynamically provide zoom level

### ISSUE THREAD

**Issue by rsaa** [ilatif/image_zoomer#7]
Is there a way to provide zoom level such as 2x, 4x,... to zoom in more or less?

**Comment by ilatif** [comment]
@rsaa Yeah! you can provide zoom level of your choice. For example

```
var options = {height: 90, width: 90, scale: 2};
```

`scale` is the option which controls zoom. Sorry for not mentioning it in `README.md`. I will update it soon.

Please let me know how this goes.

Thanks.
